### ISSUE TITLE
python SqlVisualization does not respect dict order for seriesOptions (chart legend)

### ISSUE THREAD

**Issue by Ownmarc** [pulumi/pulumi-databricks#126]
### What happened?

While deploying a dashboard visualization to databricks using the python provider, I noticed the legend of my charts were not deployed in the same order I defined them in my json of the chart options.

I made sure to use OrderedDict while loading my json file and converting it to a string.

Here is how the series are defined in my JSON file :
```
"seriesOptions": {
                "pred_sold": {
                    "yAxis": 0,
                    "type": "line",
                    "name": "Sales Predictions",
                    "color": "#356AFF"
                },
                "total_sold": {
                    "yAxis": 0,
                    "type": "line",
                    "name": "Sales Actuals",
                    "color": "#E92828"
                },
                "pred_str": {
                    "yAxis": 1,
                    "type": "line",
                    "name": "STR Predictions",
                    "color": "#00B6EB"
                },
                "event_day_str": {
                    "yAxis": 1,
                    "type": "line",
                    "name": "STR Actuals",
                    "color": "#FB8D3D"
                }
            },
```

and here is how it is showing in databricks dashboard :
![image](https://github.com/pulumi/pulumi-databricks/assets/24617457/1360f799-add5-45fc-b393-f486a8dadca6)

### Expected Behavior

The order of the seriesOptions to be the order that is showing in the deployed dashboard.

### Steps to reproduce

Deploy a chart graph in a dashboard with seriesOptions dict that is not ordered, see that the ordering gets changed on the deployed dashboard

### Output of `pulumi about`

-

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by aq17** [comment]
Hi @Ownmarc , thanks for the issue. I don't believe this is a bug in the provider – could you take a look at [this support thread ](https://community.databricks.com/s/question/0D58Y00009IJT2LSAX/wrong-xaxis-order-when-visualization-is-put-on-dashboard) and see if it may help?

**Comment by Ownmarc** [comment]
Will do, I'll report back.

**Comment by mnlumi** [comment]
Hey @Ownmarc - I'm going to close this issue. If you feel the issue resides within Pulumi, please feel free to re-open and share more details. Thanks!
