### ISSUE TITLE
Views not querable from sql warehouses

### ISSUE THREAD

**Issue by nicoladeseta** [pulumi/pulumi-databricks#148]
### What happened?

We want to create a view using the table resource provided by pulumi-databricks. The creation completes succesfully but the view is not querable from the SQL editor (by using sql warehouses). It works fine if you query it from a notebook.

The error is:

`Java.util.concurrent.ExecutionException: com.databricks.sql.managedcatalog.UnityCatalogServiceException: [RequestId=4c3ccdec-f899-4252-a26d-29df36198e62 ErrorClass=INVALID_PARAMETER_VALUE] credential requested for table 915d4226-c0a2-4913-8d92-5c32518f0c1f is not under dependent eff4dff0-49e2-42b3-bc47-17e8775124e3`

where the first is the id of the dependent table while the second is the id of the view.

### Expected Behavior

The view must be querable from anywhere as long as you have the access granted.

### Steps to reproduce

Given an existing table on databricks, define the resource as follow:

```python
args = TableArgs(
    catalog_name='data_staging',
    schema_name='test_schema2',
    table_type='VIEW',
    columns=[
        TableColumnArgs(
            name='id',
            position=0,
            type_name='STRING',
            type_text='string',
            type_json='{"name":"id","type":"string","nullable":true,"metadata":{}}',
        ),
        TableColumnArgs(
            name='name',
            position=1,
            type_name='INT',
            type_text='integer',
            type_json='{"name":"name","type":"integer","nullable":true,"metadata":{}}',
        )
    ],
    view_definition="SELECT CASE WHEN is_account_group_member('group_a') THEN id ELSE '****' END as id, hash(name) as name FROM data_staging.test_schema2.src_table'",
    data_source_format='',
    name='test_view',
)

table = Table(
    resource_name='test_view',
    args=args,
    opts=ResourceOptions(
        replace_on_changes=["*"], delete_before_replace=True
    ),
)
```

then pulumi preview and pulumi up to proceed with creation.

Once the view is created, go into SQL editor and  spin up a warehouse. Then try to run a simple select * from test_view.

### Output of `pulumi about`

CLI          
Version      3.62.0
Go Version   go1.20.2
Go Compiler  gc

Plugins
NAME        VERSION
auth0       2.21.0
aws         5.41.0
cloudamqp   3.14.0
cloudflare  4.16.0
databricks  1.15.0
datadog     4.18.1
kubernetes  3.29.0
python      unknown
random      4.13.2

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in python: executable='***/.venv/bin/python3' version='3.10.6
'

Current Stack: organization/datasets/datasets.staging

TYPE                            URN
pulumi:pulumi:Stack             urn:pulumi:datasets.staging::datasets::pulumi:pulumi:Stack::datasets-datasets.staging
databricks:index/table:Table    urn:pulumi:datasets.staging::datasets::databricks:index/table:Table::test_view
databricks:index/grants:Grants  urn:pulumi:datasets.staging::datasets::databricks:index/grants:Grants::test_view_-5639984575611493077

Found no pending operations associated with datasets.staging

Backend        
Name           L-PA-PF2SL0B2
URL            s3://pulumi-state-bucket
User           ****
Organizations  

Dependencies:
NAME               VERSION
black              22.12.0
data-prima-pulumi  0.3.0
flake8             3.9.2
isort              5.12.0
mypy               0.931.0
parameterized      0.9.0
pip                23.1.2
prima-pulumi       0.17.27
setuptools         67.7.2
wheel              0.40.0

Pulumi locates its logs in /tmp by default
warning: A new version of Pulumi is available. To upgrade from version '3.62.0' to '3.72.2', run 
   $ curl -sSL https://get.pulumi.com | sh
or visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by nicoladeseta** [comment]
Yep, we granted the SELECT permission to the right user as per documentation. We even tried with "account users" as target for the grant but it doesn't work either.

What we noticed by running the `databricks unity-catalog tables get --full-name [view]` is that:

- in case of a manually created view -> we have a "dependencies" object with the reference to the table used in the view_definition
- in case of a view created with pulumi -> the "dependencies" object is empty.

I don't know if that's related, unfortunately we haven't found a way to play with such metadata to say whether it's related or not.

**Comment by t0yv0** [comment]
Unfortunately my team is not well positioned to repro the issue, we might need to leave it in the backlog for now to see if we can get some help from the community.

One avenue to pursue here is trying to provision the view through Terraform via the upstream terraform-provider-databricks provider. Pulumi provider tries to be a thin wrapper over the upstream provider. If the issue persists with using the upstream provider directly, the ideal case would be to fix it upstream and then it would be resolved in Pulumi through a routine dependency update. 

I've scanned the upstream issue tracker but did not find anything too similar. Possibly related: https://github.com/databricks/terraform-provider-databricks/issues/1267

FWIW there's also some instructions to enable debug logging that may help shed some light on what's happening inside the Pulumi provider: https://www.pulumi.com/docs/support/troubleshooting/

**Comment by mjeffryes** [comment]
Unfortunately, it looks like this issue hasn't seen any updates in a while. If you're still encountering this problem, could you leave a quick comment to let us know so we can prioritize it? (Commenting will bump it back into our triage queue.)

**Comment by nicoladeseta** [comment]
Hello @mjeffryes, we went for another path we are no longer trying to create views via pulumi. No need to prioritize this.

**Comment by guineveresaenger** [comment]
Thank you for your followup here @nicoladeseta.
