### ISSUE TITLE
Changed DbfsFile is deleted on databricks

### ISSUE THREAD

**Issue by sebbegg** [pulumi/pulumi-databricks#18]
### What happened?

When a `DbfsFile` from a local source file is supposed to be updated / replaced on databricks, it's only deleted.

I would like to manage python script files with pulumi-databricks.
When updating the script content locally, pulumi notices the change and claims to replace the file on databricks.
However after `pulumi up` runs just fine the file is gone from databricks.

Since pulumi thinks all went well, the only workaround currently seems to be an explicit `pulumi destroy --target <dbfs-urn>`.
After that the file is properly uploaded again.

### Steps to reproduce

I reproduced the issue with a pretty minimal setup:

```python
"""A Python Pulumi program"""

import pulumi
from pulumi_databricks.dbfs_file import DbfsFile

hello_world_file = DbfsFile(
    "hello-world-script",
    source="hello-world.py",
    path="/FileStore/pulumi-databricks/hello-world.py"
)
```

with `hello-world.py` being a local python script that just prints "hello world".

Steps to reproduce:

1. Run `pulumi up` - which will create/upload the file to dbfs
2. Check: `dbfs cat dbfs:/FileStore/pulumi-databricks/hello-world.py`
3. Modify `hello-world.py` in some way
4. Run `pulumi up` - it will claim to replace the resource
5. Checking via `dbfs cat dbfs:/FileStore/pulumi-databricks/hello-world.py` shows that the file is gone

### Expected Behavior

The updated file should be updated.

### Actual Behavior

The previous version of the file is removed

### Versions used
```
venv ❯ pulumi about
CLI
Version      3.30.0
Go Version   go1.17.9
Go Compiler  gc

Plugins
NAME        VERSION
databricks  1.1.0
python      unknown

Host
OS       darwin
Version  12.4
Arch     x86_64

This project is written in python (/Users/xyz/Projekte/pulumi-databricks-test/venv/bin/python3 v3.9.12)

Current Stack: dev

TYPE                                URN
pulumi:pulumi:Stack                 urn:pulumi:dev::pulumi-databricks-test::pulumi:pulumi:Stack::pulumi-databricks-test-dev
pulumi:providers:databricks         urn:pulumi:dev::pulumi-databricks-test::pulumi:providers:databricks::default_1_1_0
databricks:index/dbfsFile:DbfsFile  urn:pulumi:dev::pulumi-databricks-test::databricks:index/dbfsFile:DbfsFile::hello-world-script


Found no pending operations associated with dev

Backend
Name           -
URL            file://~
User           -
Organizations

NAME               VERSION
pip                22.2
pulumi-databricks  1.1.0
setuptools         63.2.0
wheel              0.37.1

Pulumi locates its logs in /var/folders/9r/s7hj72y57dxdjgz8rm0jd9wx734y24/T/ by default
```

### Additional context

LogFile: 
[pulumi.log](https://github.com/pulumi/pulumi-databricks/files/9199818/pulumi.log)

From the logfile it seems there's a `DELETE` request some time after the `POST` the uploaded the updated version of the script... seems wrong 😉 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by viveklak** [comment]
I think this is probably because of the implicit create-before-delete replacement semantics for autonamed resources (you omitted the name field which means pulumi is going to autoname the resource). As you are referring to the same target path, you are indeed seeing the deletion trigger the removal of the file. You can either specify a specific name for the resource or specify the `delete_before_replace` resource option: https://www.pulumi.com/docs/reference/pkg/python/pulumi/#pulumi.ResourceOptions

**Comment by sebbegg** [comment]
> ```python
> "hello-world-script"
> ```

Hm, I don't think I've omitted the name field: In the example above the `resource_name`  is `hello-world-script` - the first positional argument?
I agree with the fix/workaround though, `delete_before_replace` fixes the issue.
