### ISSUE TITLE
Issue when creating VPC endpoint with MwsVpcEndpoint

### ISSUE THREAD

**Issue by ruaraikirkds** [pulumi/pulumi-databricks#336]
### What happened?

Hello team! 

I am running into an unexpected error when creating a Databricks VPC Endpoint using `MwsVpcEndpoint`  from the @pulumi/databricks npm package as suggested in the reference [docs](https://www.pulumi.com/registry/packages/databricks/api-docs/mwsvpcendpoint/#databricks-mwsvpcendpoint).

The error is quite vague so hoping for a little clarity as to whether this is a bug or an issue on my end. Please see below for simplified code for explanation.

Thanks! 

### Example

```typescript
import * as aws from '@pulumi/aws';
import * as databricks from '@pulumi/databricks';
...

       const vpcEndpoint = new aws.ec2.VpcEndpoint(
            'vpc-endpoint',
            {
                privateDnsEnabled: true,
                securityGroupIds: ['some-group-id'],
                serviceName: 'some-name',
                subnetIds: ['some-subnet-id'],
                tags: {
                    Name: 'vpc-endpoint',
                },
                vpcEndpointType: 'Interface',
                vpcId: 'some-vpc-id',
            },
            {
                provider: awsProvider,
            },
        );

        const workspaceVpcEndpoint = new databricks.MwsVpcEndpoint(
            'workspace-vpc-endpoint',
            {
                accountId: 'my-account-id',
                awsAccountId: 'my-aws-account-id',
                awsVpcEndpointId: vpcEndpoint.id, // The identifier of the VPC endpoint.
                region: 'us-east-1',
                vpcEndpointName: 'workspace-vpc-endpoint',
            },
            {
                provider: databricksProvider,
            },
        );
```

When running `pulumi up`, the following error is returned:

```
databricks:index:MwsVpcEndpoint (workspace-vpc-endpoint):
    error: 1 error occurred:
    	* cannot create mws vpc endpoint: Invalid endpoint
```

The AWS resource is created and passes a valid id to `MwsVpcEndpoint`, and I have created a VPC endpoint in the Databricks UI with the AWS VPC endpoint id and it creates fine.

For instance, when i manually created a VPC endpoint, then ran `pulumi up` I get the following:

```
Diagnostics:
  databricks:index:MwsVpcEndpoint (workspace-rest-apis-endpoint):
    error: 1 error occurred:
        * cannot create mws vpc endpoint: MALFORMED_REQUEST: A VPCEndpoint with aws_vpc_endpoint_id vpce-iwebfipuwerbfpiuwebfiuwebfwiu already exists.
```

### Output of `pulumi about`

CLI          
Version      3.93.0
Go Version   go1.21.3
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       darwin
Version  14.3
Arch     arm64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mjeffryes** [comment]
Unfortunately, it looks like this issue hasn't seen any updates in a while. If you're still encountering this problem, could you leave a quick comment to let us know so we can prioritize it? (Commenting will bump it back into our triage queue.)
