### ISSUE TITLE
Automatic docsgen is not working

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/pulumi-databricks#40]
The [documentation for this provider](https://www.pulumi.com/registry/packages/databricks/api-docs/) has not been updated since [its initial addition to the package registry](https://github.com/pulumi/registry/pull/876/files#diff-aa5733db93dbd1599c18b8b63e3d221e90e475f09df10a21767e689c9cc75465).

We have moved on from v0.4.0 to v1.4.0, with a few outstanding upgrades, so it appears that the automation that is running the [Publish Package Metadata(example)](https://github.com/pulumi/registry/pull/1642) job is not set up for this provider.

**Comment by iwahbe** [comment]
This appears to be fixed. The registry currently displays:
> Databricks v1.36.0 published on Friday, Apr 19, 2024 by Pulumi

That correctly reflects this provider's last release.
