### ISSUE TITLE
Pipeline edition missing "PREVIEW" option

### ISSUE THREAD

**Issue by alankritjoshi** [pulumi/pulumi-databricks#446]
### What happened?

Currently the only options available are CORE, PRO and ADVANCED.

To enable `serverless`, `PREVIEW` option is needed

### Example

https://github.com/pulumi/pulumi-databricks/blob/07d2c51799c679caf5926cb00025a61594928625/sdk/python/pulumi_databricks/pipeline.py#L44

1. Create `pipeline` with `serverless=True` and `edition=<any existing value or PREVIEW>`
2. `pulumi up`

### Output of `pulumi about`

```
CLI
Version      3.114.0
Go Version   go1.22.2
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  databricks  1.38.0
language  python      unknown

Host
OS       darwin
Version  13.6.3
Arch     arm64

This project is written in python: executable='/opt/homebrew/bin/python3' version='3.12.3'

Dependencies:
NAME                VERSION
databricks-connect  14.3.1
flows               0.1.0
ipykernel           6.29.4
ipywidgets          8.1.2
nbformat            5.10.4
pip                 24.0
pyright             1.1.361
pytest              8.2.0
ruff                0.4.2
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hi @alankritjoshi. Thanks for raising an issue. This provider is bridged from [databricks/terraform-provider-databricks](https://github.com/databricks/terraform-provider-databricks) and they don't support this feature. I would recommend [raising an enhancement request with them](https://github.com/databricks/terraform-provider-databricks/issues/new?assignees=&labels=feature&projects=&template=feature-request.md&title=%5BFEATURE%5D+New+feature+request). As soon as they release a provider that supports setting `edition` to `PREVIEW`, we will as well.

**Comment by alankritjoshi** [comment]
Tested a bit more, looks like the actual usage is:

```
channel="PREVIEW"
edition="ADVANCED"
```
