### ISSUE TITLE
Numerous Catalog Grants not supported

### ISSUE THREAD

**Issue by pmarct** [pulumi/pulumi-databricks#45]
### What happened?

Various catalog grants like "USE_SCHEMA" and "MODIFY" return "not allowed on catalog", despite their functionality existing in terraform and the databricks UI. https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/grants
https://docs.databricks.com/data-governance/unity-catalog/manage-privileges/privileges.html#inheritance

### Steps to reproduce

Set a grant to a catalog with privileges like "USE_SCHEMA", "MODIFY", etc.

### Expected Behavior

These should be valid privileges

### Actual Behavior

Error: says they aren't allowed on catalogs
`error: diffing urn:pulumi:dev::databricks-workspaces::databricks:index/grants:Grants::yellowCatalogGrant: USE_SCHEMA is not allowed on catalog`

### Output of `pulumi about`

```
CLI          
Version      3.44.1
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.18.0
databricks  1.4.0
nodejs      unknown

Host     
OS       darwin
Version  12.4
Arch     arm64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by pmarct** [comment]
https://docs.databricks.com/data-governance/unity-catalog/manage-privileges/privileges.html#inheritance

**Comment by thomas11** [comment]
Hi @pmarct, we are always prioritizing across our providers and will most likely update this provider in the next few days.

**Comment by pmarct** [comment]
@thomas11 got it, thank you

**Comment by AaronFriel** [comment]
Hey @pmarct, sorry for not replying sooner. It looks like we fixed this not long after the last message. 

If you encounter this again, please create a new issue for our team to track.
