### ISSUE TITLE
PrincipalId field of MwsPermissionAssignment is limited to int32, should be int64 or string

### ISSUE THREAD

**Issue by automagic** [pulumi/pulumi-databricks#476]
### What happened?

MwsPermissionAssignment resource currently has an input field [PrincipalId](https://www.pulumi.com/registry/packages/databricks/api-docs/mwspermissionassignment/#principalid_csharp) of type Int (32 bit). This should be at least Long, if not string , as Databricks shows principal values as much longer (e.g.,  1039977151885245).

### Example

n/a

### Output of `pulumi about`

CLI          
Version      3.111.1
Go Version   go1.22.1
Go Compiler  gc

Host     
OS       darwin
Version  14.4.1
Arch     arm64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hey @automagic. Thanks for reporting this issue.

It would be awesome if you could post a small program that reproduces the issue so we could confirm the fix.

**Comment by automagic** [comment]
@iwahbe 

```
import * as pulumi from "@pulumi/pulumi";
import * as databricks from "@pulumi/databricks";

var group = new Databricks.Group("some-group-name", new()
{
    DisplayName = "SomeGroupName"
});

var mwsPermissionAssignment = new Databricks.MwsPermissionAssignment("mws-perm-assign", new()
{
    Permissions = { "ADMIN" }, // or { "USER" }
    PrincipalId = group.Id.Apply(id => int.Parse(id)),   // group.Id is a string, which could look like '1039977151885245' (too big to parse into an int32)
    WorkspaceId = cfg.Workspace.WorkspaceId,
});
```
