### ISSUE TITLE
`get_node_type` isn't working

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi-databricks#48]
### What happened?

When calling `get_node_type()`, the operation always return `Standard_D3_v2`.

From my initial investigation, it _seems_ like there's no API call made to the provider endpoint in order to retrieve the list of supported node types. As I use a proxy (squid-cache), my network traffic is funneled there. If I run a `curl` command to the databricks endpoint, then I'm able to retrieve a JSON of supported node types. However, when I run the pulumi code provided, I don't see any traffic to the endpoint at all.

Looking at the upstream [code](https://github.com/databricks/terraform-provider-databricks/blob/master/clusters/data_node_type.go#L130-L135), if the list/json is empty, then `Standard_D3_v2` via [`defaultSmallestNodeType()`](https://github.com/databricks/terraform-provider-databricks/blob/master/clusters/data_node_type.go#L110)

The problem seem to occur with both Azure and AWS.

### Steps to reproduce

1. Create a new Pulumi app (Python) using the code below
2. Update `subscription_id` (L9), `tenant_id` (L10) 
3. Comment out `node_type = pulumi_databricks(...` (L63-76)
4. Comment out `pulumi.export("node_type", ...` (L79)
6. Run `pulumi up`
7. Once deployed, Go to the Azure portal > Resource Groups > `case-2022-db` and click 'Launch Workspace`
8. Then, in the databricks UI, top right click on your email address > User Settings > Generate Token
9. Update `db_token` (L11)
10. Enable commented code from step 3 and 4
11. Run `pulumi up`
12. Observe the `node_type` value as a stack output

I've commented some code for you to fiddle with (L65-71) but regardless of the values, the same result is shown.

Verbose logs attached below [out.txt](https://github.com/pulumi/pulumi-databricks/files/10027696/out.txt)
```
pulumi up --yes --skip-preview --verbose 9 --logtostderr 2> out.txt
```

### Expected Behavior

* The node type returned changes based on the parameters provided to select the correct node type.

### Actual Behavior

* With the code provided on Azure, `Standard_D3_v2` is always returned.

### Output of `pulumi about`

```
CLI          
Version      3.46.1
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.86.0
databricks    1.4.0
python        unknown

Host     
OS       debian
Version  11.5
Arch     x86_64

This project is written in python: executable='/home/aureq/work/customers/mbrdna/case-2022/venv/bin/python3' version='3.9.15
'

Current Stack: case-2022

TYPE                                  URN
pulumi:pulumi:Stack                   urn:pulumi:case-2022::zendesk::pulumi:pulumi:Stack::zendesk-case-2022
pulumi:providers:azure-native         urn:pulumi:case-2022::zendesk::pulumi:providers:azure-native::case-2022-az-provider
azure-native:resources:ResourceGroup  urn:pulumi:case-2022::zendesk::azure-native:resources:ResourceGroup::case-2022-rg
azure-native:databricks:Workspace     urn:pulumi:case-2022::zendesk::azure-native:databricks:Workspace::case-2022-db
pulumi:providers:databricks           urn:pulumi:case-2022::zendesk::pulumi:providers:databricks::case-2022-db-db-provider


Found no pending operations associated with case-2022

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/aureq
User           aureq
Organizations  aureq, team-ce, menfin, menfin-team, demo, pulumi

Dependencies:
NAME                 VERSION
pip                  22.3.1
pulumi-azure-native  1.86.0
pulumi-databricks    1.4.0
setuptools           65.5.1
wheel                0.38.4
```

### Additional context

Here is the Pulumi app.

```python
"""An Azure RM Python Pulumi program"""
import os
from enum import Enum
import pulumi
import pulumi_azure_native
import pulumi_databricks

# change me (x3)
subscription_id = "12345678-1234-1234-1234-1234567890ab"
tenant_id = "09876543-6789-6789-6789-ab0987654321"
db_token = "dapixxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-x"


class DatabricksNodeCategory(str, Enum):
    GENERAL_PURPOSE = "General Purpose"
    GENERAL_PURPOSE_HDD = "General Purpose (HDD)"
    COMPUTE_OPTIMIZED = "Compute Optimized"
    MEMORY_OPTIMIZED = "Memory Optimized"
    MEMORY_OPTIMIZED_REMOTE_HDD = "Memory Optimized (Remote HDD)"
    STORAGE_OPTIMIZED = "Storage Optimized"
    GPU_ACCELERATED = "GPU Accelerated"

base_name = "case-2022"
rg_name = f'{base_name}-rg'
location = "West Europe"
dbname = f'{base_name}-db'

az_provider = pulumi_azure_native.Provider(
    resource_name=f"{base_name}-az-provider",
    subscription_id=subscription_id,
    tenant_id=tenant_id
)

resource_group = pulumi_azure_native.resources.ResourceGroup(resource_name=rg_name,
    location=location,
    resource_group_name=rg_name,
    opts=pulumi.ResourceOptions(
        provider=az_provider
    )
)

workspace = pulumi_azure_native.databricks.Workspace(dbname,
    location=location,
    managed_resource_group_id=f"/subscriptions/{subscription_id}/resourceGroups/{rg_name}-dbmanaged",
    resource_group_name=rg_name,
    workspace_name=dbname,
    opts=pulumi.ResourceOptions(
        depends_on=resource_group,
        provider=az_provider
    )
)

db_provider = pulumi_databricks.Provider (
    resource_name=f"{dbname}-db-provider",
    auth_type="token",
    token=db_token,
    azure_workspace_resource_id=workspace.workspace_id,
    host=workspace.workspace_url,
    http_timeout_seconds=90,
    azure_tenant_id=tenant_id,
)

node_type = pulumi_databricks.get_node_type(
    min_cores=32,
    # local_disk=True,
    # gb_per_core=1,
    # min_gpus=1,
    # category=DatabricksNodeCategory.GENERAL_PURPOSE,
    # min_memory_gb=56,
    # min_cores=16,
    # local_disk=1,
    opts=pulumi.InvokeOptions(
        provider=db_provider,
        parent=db_provider
    )
)

pulumi.export("url", workspace.workspace_url)
pulumi.export("node_type", node_type.id)
```

Here is the cURL command I used to get the JSON [node_types.zip](https://github.com/pulumi/pulumi-databricks/files/10027712/node_types.zip). The correct base host is obtained via `workspace.workspace_url`.

```bash
curl -X GET -H 'Authorization: Bearer <datasbricksToken>' 'https://adb-XXXXXXXXXXXXXXXX.XX.azuredatabricks.net/api/2.0/clusters/list-node-types' | jq . > node_types.json
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
Thanks for the detailed report!

Checked that both Python and Go (as sanity check) SDKs invoke the provider's `databricks:index/getNodeType:getNodeType` function. Digging further.

**Comment by thomas11** [comment]
This comment in the TF provider, just before the part you linked to, is suspicious:

```go
func (a ClustersAPI) GetSmallestNodeType(r NodeTypeRequest) string {
	list, _ := a.ListNodeTypes()
	// error is explicitly ingored here, because Azure returns
	// apparently too big of a JSON for Go to parse
```

The call to `ListNodeTypes` could fail for any number of reasons. I might have to step through in a debugger.

**Comment by aureq** [comment]
ok, so by the sound of it, there's a data source that's not functional if I read your comment correctly, right?

**Comment by thomas11** [comment]
Turns out the data source is functional, just sparsely documented and it doesn't surface errors you would need to see.

I finally found time to set up (very well documented!) repro and step through in the debugger. What happens is that the query to list node types fails in the setup phase before it's sent (hence you don't see it in the proxy).

```
"cannot configure token auth. Attributes used: auth_type, azure_tenant_id, azure_workspace_resource_id, host, token. Please check https://registry.terraform.io/providers/databricks/databricks/latest/docs#authentication for details"
```

That's why we don't swallow errors as in the `// error is explicitly ingored here` above...

After a bit more experimentation, it turns out it's a misunderstanding in how the provider is configured in your program. 

```
    auth_type="token",
    token=db_token,
```

The `token` property is meant for token-based authentication to the cloud provider, not to Databricks.

Simply removing those two, and setting `databricks:token` and `databricks:host` instead [as per our docs](https://www.pulumi.com/registry/packages/databricks/installation-configuration/#configuring-credentials), makes the authentication part succeed for me (after prior `az login`).

The API request then fails server-side with "400 Invalid resource ID" but that's probably easily fixable.

I hope that helps!

**Comment by aureq** [comment]
@thomas11 this doesn't seem to work for me unfortunately...

Here's a snippet of the code I changed

```python
# [...]
db_provider = pulumi_databricks.Provider (
    resource_name=f"{dbname}-db-provider",
    # auth_type="token",
    # token=db_token,
    azure_workspace_resource_id=workspace.workspace_id,
    host=workspace.workspace_url,
    http_timeout_seconds=90,
    azure_tenant_id=tenant_id,
)

node_type = pulumi_databricks.get_node_type(
    min_cores=16,
    # local_disk=True,
    # gb_per_core=1,
    # min_gpus=1,
    category=DatabricksNodeCategory.GENERAL_PURPOSE_HDD,
    # min_memory_gb=56,
    # min_cores=16,
    # local_disk=1,
    opts=pulumi.InvokeOptions(
        provider=db_provider,
        parent=db_provider
    )
)
# [...]
```

```yaml
config:
  azure-native:location: West Europe
  databricks:host: adb-5758842155562043.3.azuredatabricks.net
  databricks:token:
    secure: AAABAC14nm1wwRvqG77MbMfbf70So3HutDQfFpzu/DPRZxHxt38EsnH+n0ZQ1+rCck2HEEjmyt/Y/BhPoOA/8K5bE/gcTQ==
```

```log
I1121 11:12:22.444219   19052 eventsink.go:59] Using Azure CLI authentication with AAD tokens
I1121 11:12:22.444276   19052 eventsink.go:62] eventSink::Debug(<{%reset%}>Using Azure CLI authentication with AAD tokens<{%reset%}>)
I1121 11:12:22.985069   19052 eventsink.go:59] Refreshed OAuth token for https://management.core.windows.net/ from Azure CLI, which expires on 2022-11-21 12:26:15.000000
I1121 11:12:22.985124   19052 eventsink.go:62] eventSink::Debug(<{%reset%}>Refreshed OAuth token for https://management.core.windows.net/ from Azure CLI, which expires on 2022-11-21 12:26:15.000000<{%reset%}>)
I1121 11:12:23.561706   19052 eventsink.go:59] Refreshed OAuth token for 2ff814a6-3304-4ab8-85cb-cd0e6f879c1d from Azure CLI, which expires on 2022-11-21 11:39:58.000000
I1121 11:12:23.561778   19052 eventsink.go:62] eventSink::Debug(<{%reset%}>Refreshed OAuth token for 2ff814a6-3304-4ab8-85cb-cd0e6f879c1d from Azure CLI, which expires on 2022-11-21 11:39:58.000000<{%reset%}>)
I1121 11:12:23.562174   19052 eventsink.go:59] Configured azure-cli auth: host=https://adb-5758842155562043.3.azuredatabricks.net, azure_workspace_resource_id=5758842155562043, azure_tenant_id=706143bc-e1d4-4593-aee2-c9dc60ab9be7
I1121 11:12:23.562212   19052 eventsink.go:62] eventSink::Debug(<{%reset%}>Configured azure-cli auth: host=https://adb-5758842155562043.3.azuredatabricks.net, azure_workspace_resource_id=5758842155562043, azure_tenant_id=706143bc-e1d4-4593-aee2-c9dc60ab9be7<{%reset%}>)
I1121 11:12:23.562675   19052 eventsink.go:59] GET /api/2.0/clusters/list-node-types 
I1121 11:12:23.562710   19052 eventsink.go:62] eventSink::Debug(<{%reset%}>GET /api/2.0/clusters/list-node-types <{%reset%}>)
I1121 11:12:24.678530   19052 eventsink.go:59] 400 Bad Request [non-JSON document of 286 bytes]
I1121 11:12:24.678594   19052 eventsink.go:62] eventSink::Debug(<{%reset%}>400 Bad Request [non-JSON document of 286 bytes]<{%reset%}>)
I1121 11:12:24.679185   19052 eventsink.go:59] /api/2.0/clusters/list-node-types:400 - Invalid resource ID https://docs.databricks.com/dev-tools/api/latest/clusters.html#list-node-types
I1121 11:12:24.679245   19052 eventsink.go:62] eventSink::Debug(<{%reset%}>/api/2.0/clusters/list-node-types:400 - Invalid resource ID https://docs.databricks.com/dev-tools/api/latest/clusters.html#list-node-types<{%reset%}>)
I1121 11:12:24.679944   19052 rpc.go:274] Unmarshaling property for RPC[Provider[databricks, 0xc0009ddc20].Invoke(databricks:index/getNodeType:getNodeType).returns]: category={General Purpose}
I1121 11:12:24.679987   19052 rpc.go:274] Unmarshaling property for RPC[Provider[databricks, 0xc0009ddc20].Invoke(databricks:index/getNodeType:getNodeType).returns]: id={Standard_D3_v2}
I1121 11:12:24.680004   19052 rpc.go:274] Unmarshaling property for RPC[Provider[databricks, 0xc0009ddc20].Invoke(databricks:index/getNodeType:getNodeType).returns]: minCores={16}
I1121 11:12:24.680032   19052 provider_plugin.go:1357] Provider[databricks, 0xc0009ddc20].Invoke(databricks:index/getNodeType:getNodeType) success (#ret=3,#failures=0) success
```

And from your comment, I have a few questions.

* What are the differences as to why it's working for you and not me? (happy to work together when you're back on Monday)
* How to configure the provider programmatically? (ie, not via env nor `Pulumi.<stack>.yaml`? (I could trick using `os.environ` but it doesn't feel _clean_. In the logs above, seems to be using AAD token though.
* If the provider isn't set correctly, why no error is shown? because that adds a lot of confusion to the user.
* setting `DATABRICKS_HOST` and `DATABRICKS_TOKEN` results in an error `More than one authorization method configured: azure and token` but not when `databricks:host` and `databricks:token` are set in the YAML which is also confusing.

Thank you.

**Comment by thomas11** [comment]
Seems like it's working for you, no? Note that I said above

>The API request then fails server-side with "400 Invalid resource ID" but that's probably easily fixable.

Like for you. You should debug why that is, but we're a step further.

As to how to configure a provider programmatically, you can do this with [explicit providers](https://www.pulumi.com/docs/intro/concepts/resources/providers/#explicit-provider-configuration).

**Comment by aq17** [comment]
Going to close this as stale since there have been quite a few releases of the provider since, and it seems like this may not be an issue with the provider itself – please reopen if any further issues/ questions!
