### ISSUE TITLE
C# WorkspaceId type incorrectly an Int

### ISSUE THREAD

**Issue by jimconstable** [pulumi/pulumi-databricks#55]
### What happened?

If you try to pass any actual workspaceId to MetastoreAssignment the workspaceId is too large for the Int type. 

### Steps to reproduce

Try and create a metastoreAssignment resource in C#. 

### Expected Behavior

I would be able to cast the workspaceId which was a string in the Azure Native Databricks Workspace resource into an Int.   

### Actual Behavior

The int.Parse failed. 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by roothorp** [comment]
Hi @jimconstable, thanks for the issue! I've passed this along to the team to appropriately prioritize and add to our work stack.

It looks like upstream the workspaceId is an `int64`, but here we're using `int`.

**Comment by dbeattie71** [comment]
Is there a workaround for linking a Metastore to a Workspace?

**Comment by automagic** [comment]
Same issue with `MwsPermissionAssignment` resource

**Comment by VenelinMartinov** [comment]
Hey folks, thanks for bringing this to our attention, this looks like an instance of https://github.com/pulumi/pulumi-terraform-bridge/issues/1342, we'll prioritize this as soon as we can.
