### ISSUE TITLE
docs: Resource documentation `databricks.Permissions` shows HCL code

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi-databricks#557]
### Describe what happened

When reading the documentation for [`databricks.Permissions`](https://www.pulumi.com/registry/packages/databricks/api-docs/permissions/), the page shows broken HCL code.

### Sample program

n/a

### Log output

n/a

### Affected Resource(s)

n/a

### Output of `pulumi about`

n/a

### Additional context

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
Thanks for reporting this - we will take a look at fixing this ASAP.
