### ISSUE TITLE
Proper way to define dependencies between schema and objects within

### ISSUE THREAD

**Issue by sebbegg** [pulumi/pulumi-databricks#583]
Hi,

we use pulumi-databricks to deploy our schemas, volumes etc. in unity catalog.
One odd behavior I noticed is what happens if pulumi needs to recreate a schema:

* The plan correctly shows a `replace` for the schema (e.g. because we change the `storage_root`), which is expected
* All the resources within (mostly volumes in our case) appear to be unaffected by this though

So, what happens is that pulumi delete-replaces the schema but does not anticipate that all the child-resources would need to be recreated as well.
All the volumes in the schema do depend on the schema (as we use `schema.name`), but this doesn't seem to help.
I've also set `deleted_with = schema` in the volumes, with - apparently - no effect.

Is there a way (e.g. using `parent`?) to properly handle this without needing e.g. a refresh after such a deployment?

If required I can probably put together an example.

**Comment by guineveresaenger** [comment]
Hi @sebbegg - sorry you're having trouble here.

We recommend looking into the [`dependsOn` resource option](https://www.pulumi.com/docs/concepts/options/dependson/) to specify dependency relationships between resources.

Please let us know if this resoles your issue; if you're still struggling, we'd love to see a minimal example in case it's a bug.

**Comment by sebbegg** [comment]
Not sure why - but couldn't reproduce :(
We're already using `dependsOn` - in newer attempts the sequence worked as expected

**Comment by guineveresaenger** [comment]
Thank you for the update here @sebbegg. Let us know if the problem appears again!
