### ISSUE TITLE
error: could not validate provider configuration: 4 errors occurred

### ISSUE THREAD

**Issue by XBeg9** [pulumi/pulumi-databricks#9]
### What happened?

I can't create databricks provider

### Steps to reproduce

```js
export const provider = new Provider(
  'databricks',
  {
    azureWorkspaceResourceId: workspace.id,
    azureClientId: config.azure.clientId,
    azureTenantId: config.azure.tenantId,
    azureClientSecret: config.azure.clientSecret,
    host: workspace.workspaceUrl
  },
  {
    parent: workspace
  }
);
```

### Expected Behavior

It should create a provider and allow to use it

### Actual Behavior

```error: could not validate provider configuration: 4 errors occurred:
        * : invalid or unknown key: azure_client_id
        * : invalid or unknown key: azure_client_secret
        * : invalid or unknown key: azure_tenant_id
        * : invalid or unknown key: azure_workspace_resource_id
```

### Versions used

CLI          
Version      3.33.2
Go Version   go1.18.2
Go Compiler  gc

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment]
Just to add to the issue that @XBeg9 and I are talking about this in slack right now. I am not able to recreate this as the video shows

https://asciinema.org/a/kHk2w68v4hkijUvU05Sw6zsPB

But we are continuing to evaluate

**Comment by XBeg9** [comment]
This is can't be replicated in a fresh new environment (tested in devcontainer, everything works like a charm). Thanks, @stack72 for debugging, appreciate your help!

**Comment by stack72** [comment]
Always happy to help! Thanks for closing this out :)
